// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: printbuff.proto

package printm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Savelocation string `protobuf:"bytes,2,opt,name=savelocation,proto3" json:"savelocation,omitempty"`
	Organization string `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
}

func (x *PrintMsg) Reset() {
	*x = PrintMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printbuff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintMsg) ProtoMessage() {}

func (x *PrintMsg) ProtoReflect() protoreflect.Message {
	mi := &file_printbuff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintMsg.ProtoReflect.Descriptor instead.
func (*PrintMsg) Descriptor() ([]byte, []int) {
	return file_printbuff_proto_rawDescGZIP(), []int{0}
}

func (x *PrintMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PrintMsg) GetSavelocation() string {
	if x != nil {
		return x.Savelocation
	}
	return ""
}

func (x *PrintMsg) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type PrintResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result   bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Strerror string `protobuf:"bytes,3,opt,name=strerror,proto3" json:"strerror,omitempty"`
}

func (x *PrintResult) Reset() {
	*x = PrintResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printbuff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResult) ProtoMessage() {}

func (x *PrintResult) ProtoReflect() protoreflect.Message {
	mi := &file_printbuff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResult.ProtoReflect.Descriptor instead.
func (*PrintResult) Descriptor() ([]byte, []int) {
	return file_printbuff_proto_rawDescGZIP(), []int{1}
}

func (x *PrintResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PrintResult) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *PrintResult) GetStrerror() string {
	if x != nil {
		return x.Strerror
	}
	return ""
}

var File_printbuff_proto protoreflect.FileDescriptor

var file_printbuff_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x73, 0x61, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x74, 0x72, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x2c, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x6e,
	0x74, 0x6d, 0x12, 0x22, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x51, 0x72, 0x12, 0x09, 0x2e,
	0x50, 0x72, 0x69, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x6d, 0x3b, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_printbuff_proto_rawDescOnce sync.Once
	file_printbuff_proto_rawDescData = file_printbuff_proto_rawDesc
)

func file_printbuff_proto_rawDescGZIP() []byte {
	file_printbuff_proto_rawDescOnce.Do(func() {
		file_printbuff_proto_rawDescData = protoimpl.X.CompressGZIP(file_printbuff_proto_rawDescData)
	})
	return file_printbuff_proto_rawDescData
}

var file_printbuff_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_printbuff_proto_goTypes = []interface{}{
	(*PrintMsg)(nil),    // 0: PrintMsg
	(*PrintResult)(nil), // 1: PrintResult
}
var file_printbuff_proto_depIdxs = []int32{
	0, // 0: Printm.PrintQr:input_type -> PrintMsg
	1, // 1: Printm.PrintQr:output_type -> PrintResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_printbuff_proto_init() }
func file_printbuff_proto_init() {
	if File_printbuff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_printbuff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_printbuff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_printbuff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_printbuff_proto_goTypes,
		DependencyIndexes: file_printbuff_proto_depIdxs,
		MessageInfos:      file_printbuff_proto_msgTypes,
	}.Build()
	File_printbuff_proto = out.File
	file_printbuff_proto_rawDesc = nil
	file_printbuff_proto_goTypes = nil
	file_printbuff_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrintmClient is the client API for Printm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrintmClient interface {
	PrintQr(ctx context.Context, in *PrintMsg, opts ...grpc.CallOption) (*PrintResult, error)
}

type printmClient struct {
	cc grpc.ClientConnInterface
}

func NewPrintmClient(cc grpc.ClientConnInterface) PrintmClient {
	return &printmClient{cc}
}

func (c *printmClient) PrintQr(ctx context.Context, in *PrintMsg, opts ...grpc.CallOption) (*PrintResult, error) {
	out := new(PrintResult)
	err := c.cc.Invoke(ctx, "/Printm/PrintQr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrintmServer is the server API for Printm service.
type PrintmServer interface {
	PrintQr(context.Context, *PrintMsg) (*PrintResult, error)
}

// UnimplementedPrintmServer can be embedded to have forward compatible implementations.
type UnimplementedPrintmServer struct {
}

func (*UnimplementedPrintmServer) PrintQr(context.Context, *PrintMsg) (*PrintResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintQr not implemented")
}

func RegisterPrintmServer(s *grpc.Server, srv PrintmServer) {
	s.RegisterService(&_Printm_serviceDesc, srv)
}

func _Printm_PrintQr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintmServer).PrintQr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Printm/PrintQr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintmServer).PrintQr(ctx, req.(*PrintMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Printm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Printm",
	HandlerType: (*PrintmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrintQr",
			Handler:    _Printm_PrintQr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "printbuff.proto",
}
